# Generated by Django 3.2.3 on 2021-05-24 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210523_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_use', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('review', models.TextField(max_length=500)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=5)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe')),
            ],
        ),
    ]
