# Generated by Django 3.1.7 on 2021-05-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210525_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(default='oz', max_length=20),
        ),
    ]
