# Generated by Django 3.1.7 on 2021-05-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_ingredient_measurement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='ingred_name',
        ),
    ]
