# Generated by Django 3.1.7 on 2021-05-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20210527_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipelog',
            name='rating',
            field=models.CharField(choices=[('One', 'ONE'), ('Two', 'TWO'), ('Three', 'THREE'), ('Four', 'FOUR'), ('Five', 'FIVE')], default='One', max_length=20),
        ),
    ]
