# Generated by Django 3.1.7 on 2021-05-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20210527_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipelog',
            name='rating',
            field=models.CharField(choices=[('One Star', '★'), ('Two Star', '★★'), ('Three Star', '★★★'), ('Four Star', '★★★★'), ('Five Star', '★★★★★')], default='One Star', max_length=20),
        ),
    ]
