# Generated by Django 3.2.3 on 2021-05-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_recipe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='ingredient_name',
        ),
    ]
