# Generated by Django 3.1.7 on 2021-05-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210525_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipelog',
            old_name='name',
            new_name='review_name',
        ),
    ]
