# Generated by Django 3.1.7 on 2021-05-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210526_1648'),
        ('main_app', '0005_photo'),
    ]

    operations = [
    ]
